--swiftversion 5.0

# format options
--indent 4
--self init-only
--commas inline
--trimwhitespace nonblank-lines
--hexliteralcase lowercase

--header "// Created by 박기우 on YYYY-MM-DD"

# file options
--exclude Pods, TimeCamera/AppDelegate.swift, TimeCamera/SceneDelegate.swift

# rules
